[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
MCMCChains = "c7f686f2-ff18-58e9-bc7b-31028e88f75d"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SimulatedNeuralMoments = "43b7c8c0-5622-45b8-90a3-338fc50d2232"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"
